plugins { id 'com.android.application'; id 'org.jetbrains.kotlin.android' }
android {
  namespace 'com.sf4loader'
  compileSdk 34
  defaultConfig { applicationId 'com.sf4loader'; minSdk 26; targetSdk 34; versionCode 1; versionName '1.0' }
  sourceSets { getByName('main') { jniLibs.srcDirs('src/main/jniLibs') } }
}
